CREATE TABLE `TBL_CMV_CLIENTE` 
(
	`ID_CLIENTE` INT(11) NOT NULL AUTO_INCREMENT, 
	`NOMBRE` VARCHAR(255)  NULL , 
	`APELLIDO_PATERNO` VARCHAR(255)  NULL , 
	`APELLIDO_MATERNO` VARCHAR(255)  NULL , 
	`RFC` VARCHAR(20)  NULL , `CURP` VARCHAR(20)  NULL , 
	`FECHA_ALTA` DATETIME  NULL ,
	PRIMARY KEY (`ID_CLIENTE`)
	);

CREATE TABLE `CAT_CMV_TIPO_CUENTA` 
(
	`ID_CUENTA` INT(11) NOT NULL AUTO_INCREMENT, 
	`NOMBRE_CUENTA` VARCHAR(255)  NULL , 
	PRIMARY KEY (`ID_CUENTA`)
	);

CREATE TABLE `TBL_CMV_CLIENTE_CUENTA` 
(
	`ID_CLIENTE_CUENTA` INT(11) NOT NULL AUTO_INCREMENT, 
	`ID_CLIENTE` INT(11)  NULL , 
	`ID_CUENTA` INT(11)  NULL , 
	`SALDO_ACTUAL` DECIMAL(18,8)  NULL , 
	`FECHA_CONTRATACION` DATETIME  NULL ,
	`FECHA_ULTIMO_MOVIMIENTO` DATETIME  NULL ,
	PRIMARY KEY (`ID_CLIENTE_CUENTA`),
	CONSTRAINT `FK_CLIENTE` FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `TBL_CMV_CLIENTE` (`ID_CLIENTE`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_TIPO_CUENTA` FOREIGN KEY (`ID_CUENTA`)
    REFERENCES `CAT_CMV_TIPO_CUENTA` (`ID_CUENTA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	);

-- PROCEDIMIENTO PARA LISTAR LAS CUENTAS DE UN CLIENTE
DELIMITER //
CREATE PROCEDURE `cuentas_por_idCliente` (`p_idCliente` INT)
BEGIN
  SELECT * FROM tbl_cmv_cliente_cuenta 
	LEFT JOIN cat_cmv_tipo_cuenta ON cat_cmv_tipo_cuenta.ID_CUENTA = tbl_cmv_cliente_cuenta.ID_CUENTA 
	WHERE tbl_cmv_cliente_cuenta.ID_CLIENTE = `p_idCliente` ;
END //


-- PROCEDIMIENTO PARA BORRAR UN TIPO DE CUENTA
-- PRIMERO BORRA DE LA TABLA CLIENTE_CUENTA TODAS LAS RELACIONES QUE HAY CON EL TIPO DE CUENTA QUE SE VA A BORRAR
-- UNA VEZ QUE NO HAY RELACIONES DE LLAVES FORANEAS, SE PROCEDE A ELIMINAR EL TIPO DE CUENTA
DELIMITER //
CREATE PROCEDURE `borrar_tipo_cuenta` (`p_id_TipoCuenta` INT)
BEGIN
  UPDATE tbl_cmv_cliente_cuenta 
  SET tbl_cmv_cliente_cuenta.ID_CUENTA = NULL 
  WHERE tbl_cmv_cliente_cuenta.ID_CUENTA = `p_id_TipoCuenta` ;
  DELETE FROM cat_cmv_tipo_cuenta WHERE cat_cmv_tipo_cuenta.ID_CUENTA = `p_id_TipoCuenta` ;
END //