CREATE TABLE `TBL_CMV_CLIENTE` 
(
	`ID_CLIENTE` INT(11) NOT NULL AUTO_INCREMENT, 
	`NOMBRE` VARCHAR(255)  NULL , 
	`APELLIDO_PATERNO` VARCHAR(255)  NULL , 
	`APELLIDO_MATERNO` VARCHAR(255)  NULL , 
	`RFC` VARCHAR(20)  NULL , `CURP` VARCHAR(20)  NULL , 
	`FECHA_ALTA` DATETIME  NULL ,
	PRIMARY KEY (`ID_CLIENTE`)
	);

CREATE TABLE `CAT_CMV_TIPO_CUENTA` 
(
	`ID_CUENTA` INT(11) NOT NULL AUTO_INCREMENT, 
	`NOMBRE_CUENTA` VARCHAR(255)  NULL , 
	PRIMARY KEY (`ID_CUENTA`)
	);

CREATE TABLE `TBL_CMV_CLIENTE_CUENTA` 
(
	`ID_CLIENTE_CUENTA` INT(11) NOT NULL AUTO_INCREMENT, 
	`ID_CLIENTE` INT(11)  NULL , 
	`ID_CUENTA` INT(11)  NULL , 
	`SALDO_ACTUAL` DECIMAL(18,8)  NULL , 
	`FECHA_CONTRATACION` DATETIME  NULL ,
	`FECHA_ULTIMO_MOVIMIENTO` DATETIME  NULL ,
	PRIMARY KEY (`ID_CLIENTE_CUENTA`),
	CONSTRAINT `FK_CLIENTE` FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `TBL_CMV_CLIENTE` (`ID_CLIENTE`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_TIPO_CUENTA` FOREIGN KEY (`ID_CUENTA`)
    REFERENCES `CAT_CMV_TIPO_CUENTA` (`ID_CUENTA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	);


